config/routes.rb
Rails.application.routes.draw do

  resources :demo_models

  root :to => 'home#index'

end

app/models/demo_model.rb
class DemoModel < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demo_models_controller.rb
class DemoModelsController < ApplicationController
  before_action :set_demo_model, only: [:show, :edit, :update, :destroy]

  # GET /demo_models
  # GET /demo_models.json
  def index
    @demo_models = DemoModel.all
  end

  # GET /demo_models/1
  # GET /demo_models/1.json
  def show
  end

  # GET /demo_models/new
  def new
    @demo_model = DemoModel.new
  end

  # GET /demo_models/1/edit
  def edit
  end

  # POST /demo_models
  # POST /demo_models.json
  def create
    @demo_model = DemoModel.new(demo_model_params)

    respond_to do |format|
      if @demo_model.save
        format.html { redirect_to @demo_model, notice: 'Demo model was successfully created.' }
        format.json { render :show, status: :created, location: @demo_model }
      else
        format.html { render :new }
        format.json { render json: @demo_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demo_models/1
  # PATCH/PUT /demo_models/1.json
  def update
    respond_to do |format|
      if @demo_model.update(demo_model_params)
        format.html { redirect_to @demo_model, notice: 'Demo model was successfully updated.' }
        format.json { render :show, status: :ok, location: @demo_model }
      else
        flash[:alert] = 'Validation error, could not update the model.'
        format.html { render :edit }
        format.json { render json: @demo_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demo_models/1
  # DELETE /demo_models/1.json
  def destroy
    @demo_model.destroy
    respond_to do |format|
      format.html { redirect_to demo_models_url, notice: 'Demo model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo_model
      @demo_model = DemoModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_model_params
      params.require(:demo_model).permit(:name, :date_field, :dateTime_field, :time_field, :comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_models_helper.rb
module DemoModelsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/demo_models/_fields.html.erb
<div class="row form-inputs">
  <div class="row col-sm-12 col-md-8 col-lg-8">
    <%= f.input :name, :label => 'Title', required: true, :disabled => disabled %>
    <%= f.input :date_field, as: :date_picker, :label => 'Date field', :disabled => disabled,
                input_html: {data: {date_options: {
                        defaultDate: '2012/12/25',
                        showClose: true
                }}} %>
    <%= f.input :dateTime_field, as: :datetime_picker, :label => 'DateTime field', :disabled => disabled %>
    <%= f.input :time_field, as: :time_picker, :label => 'Time field', :disabled => disabled %>
    <!--<div class='row datetimerange'>-->
      <% #= f.input :publish_date, as: :datetime_picker, wrapper: :ranged_datetime %>
      <% #= f.input :expiration_date, as: :datetime_picker, wrapper: :ranged_datetime %>
    <!--</div>-->
    <%= f.input :comment, :label => 'Comment', :disabled => disabled %>
  </div>
</div>

app/views/demo_models/_form.html.erb
<%- model_class = DemoModel -%>

<%= simple_form_for @demo_model, wrapper: :horizontal_form, :html => { :class => 'form-horizontal' } do |f| %>

    <%= f.error_notification %>

    <%= render('fields', f: f, demo_model: @demo_model, disabled: disabled)  %>

    <div class="row form-actions col-sm-6 col-md-6 col-lg-6">
      <%= link_to 'Back',:back, :class => 'btn btn-primary'  %>
      <% if !disabled %>
          <%= f.button :submit, :value => 'Save', :class => "btn btn-primary" %>
      <% else %>
          <%= link_to "Edit", edit_demo_model_path(@demo_model), :class => 'btn btn-small btn-primary' %>
      <% end %>
    </div>
<% end %>

app/views/demo_models/edit.html.erb
<div class="page-header col-sm-12">
  <div  class="container ">
    <div class="col-sm-5">
      <span class="lead text-info"><%=t '.title', :default => "Editing Demo Model" %></span>
    </div>
    <div class="col-sm-4">
    </div>
  </div>
</div>

<%= render 'form', disabled: false %>

app/views/demo_models/index.html.erb
<div class="page-header col-sm-12">
  <div  class="container ">
    <div class="col-sm-3">
      <span class="lead text-info"><%=t '.title', :default => "Listing Demo Models" %></span>
    </div>
    <div class="col-sm-9">
    </div>
  </div>
</div>

<div class="container col-sm-12">
    <table id="course_table" class="table table-striped table-bordered table-condensed" >
      <thead>
        <tr>
          <th>Name</th>
          <th>Date field</th>
          <th>Datetime filed</th>
          <th>Time field</th>
          <th>Comment</th>
          <th colspan="3">Functions</th>
        </tr>
      </thead>

      <tbody>
        <% @demo_models.each do |demo_model| %>
          <tr>
            <td><%= demo_model.name %></td>
            <td><%= demo_model.date_field %></td>
            <td><%= demo_model.dateTime_field %></td>
            <td><%= demo_model.time_field %></td>
            <td><%= demo_model.comment %></td>
            <td><%= link_to 'Show', demo_model %></td>
            <td><%= link_to 'Edit', edit_demo_model_path(demo_model) %></td>
            <td><%= link_to 'Destroy', demo_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


    <br>

    <%= link_to 'New Demo model', new_demo_model_path %>
</div>

app/views/demo_models/new.html.erb
<div class="page-header col-sm-12">
  <div  class="container ">
    <div class="col-sm-3">
      <span class="lead text-info"><%=t '.title', :default => "New Demo Model" %></span>
    </div>
    <div class="ol-sm-9">
    </div>
  </div>
</div>

<%= render 'form', disabled: false %>

app/views/demo_models/show.html.erb
<div class="page-header col-sm-12">
  <div  class="container ">
    <div class="col-sm-6">
      <span class="lead text-info"><%=t '.title', :default => "Demo Model Details" %></span>
    </div>
    <div class="col-sm-3">
    </div>
  </div>
</div>
<p id="notice"><%= notice %></p>

<%= render 'form', disabled: true %>

app/views/home/index.html.erb
<script language="javascript">
    window.location = "/demo_models";
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DateTimeDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>